apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gigsberg-app.fullname" . }}
  labels:
    app: gigsberg
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gigsberg
  template:
    metadata:
      labels:
        app: gigsberg
    spec:
      containers:
        - name: gigsberg
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
