apiVersion: v1
kind: Service
metadata:
  name: gigsberg-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gigsberg
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort | default 30080 }}
